import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';
import {
  bytesToIntLE,
  intToBytesLE,
  mikrotikKcdsaPublicKey,
  mikrotikKcdsaSign,
  mikrotikKcdsaVerify,
  __internal,
} from '../src/Kcdsa';

const { G, scalarMul, pointAdd } = __internal;

function hex(n: bigint): string {
  return n.toString(16).padStart(64, '0');
}

// Generated by running toyecc's exact point-addition/doubling/scalar-mult formulas in a real
// Python interpreter (scratch script, not committed) against this curve's real G — independent
// ground truth for the field arithmetic and group law, not just internal self-consistency. See
// the script that produced this: it re-derives the formulas from the conversation notes rather
// than importing toyecc itself, so this checks the FORMULAS, not just "does toyecc agree with
// itself".
const vectorsPath = new URL('./fixtures/mikrotik-kcdsa-curve-vectors.json', import.meta.url);
const PYTHON_SCALAR_MUL_VECTORS: { scalar: string; x: string; y: string }[] = JSON.parse(
  readFileSync(vectorsPath, 'utf8'),
);

describe('Curve25519 point arithmetic matches an independent Python reference', () => {
  it('loaded a non-trivial vector set', () => {
    expect(PYTHON_SCALAR_MUL_VECTORS.length).toBeGreaterThan(5);
  });

  for (const { scalar, x, y } of PYTHON_SCALAR_MUL_VECTORS) {
    it(`scalarMul(${scalar}, G) matches Python`, () => {
      const result = scalarMul(BigInt(scalar), G) as { x: bigint; y: bigint };
      expect(hex(result.x)).toBe(x);
      expect(hex(result.y)).toBe(y);
    });
  }

  it('matches RFC 7748 section 6.1 published test vectors (independent external standard, not just self-consistency)', () => {
    // Extracted verbatim (by line number, no manual retyping) from the raw RFC 7748 text fetched
    // via curl -- NOT through a model-mediated fetch, which was independently found to corrupt hex
    // digits. Private keys here are RFC's raw (unclamped) test scalars; RFC 7748's own
    // decodeScalar25519 clamping is applied below before scalar multiplication, exactly as X25519
    // itself would (this clamping is test-only, NOT part of Kcdsa's production sign path, which
    // deliberately does not clamp the private key scalar).
    const rfcVectorsPath = new URL(
      './fixtures/mikrotik-kcdsa-rfc7748-vectors.json',
      import.meta.url,
    );
    const rfcVectors: { name: string; privateKeyHex: string; expectedPublicKeyHex: string }[] =
      JSON.parse(readFileSync(rfcVectorsPath, 'utf8'));
    expect(rfcVectors.length).toBe(2);

    function hexToBytesLE(h: string): Uint8Array {
      const out = new Uint8Array(h.length / 2);
      for (let i = 0; i < out.length; i++) out[i] = parseInt(h.slice(i * 2, i * 2 + 2), 16);
      return out;
    }
    function decodeLE(bytes: Uint8Array): bigint {
      let v = 0n;
      for (let i = bytes.length - 1; i >= 0; i--) v = (v << 8n) | BigInt(bytes[i]);
      return v;
    }
    function clampScalar25519(bytes: Uint8Array): bigint {
      const b = bytes.slice();
      b[0] &= 0xf8;
      b[31] &= 0x7f;
      b[31] |= 0x40;
      return decodeLE(b);
    }

    for (const { name, privateKeyHex, expectedPublicKeyHex } of rfcVectors) {
      const scalar = clampScalar25519(hexToBytesLE(privateKeyHex));
      const result = scalarMul(scalar, G) as { x: bigint };
      const expected = decodeLE(hexToBytesLE(expectedPublicKeyHex));
      expect(result.x, name).toBe(expected);
    }
  });

  it('point addition and doubling agree with repeated scalar multiplication (3G+5G=8G, 3G+3G=6G)', () => {
    const p3 = scalarMul(3n, G);
    const p5 = scalarMul(5n, G);
    const p8viaAdd = pointAdd(p3, p5) as { x: bigint };
    const p8direct = scalarMul(8n, G) as { x: bigint };
    expect(p8viaAdd.x).toBe(p8direct.x);

    const p6viaDouble = pointAdd(p3, p3) as { x: bigint };
    const p6direct = scalarMul(6n, G) as { x: bigint };
    expect(p6viaDouble.x).toBe(p6direct.x);
  });
});

// Cross-language ground truth: generated by calling the real Python `kcdsaSign(data, privateKey,
// fixed_nonce_secret=...)` (`tools/mikrotik_license/signature.py`) directly, pinning the one
// genuinely random input (the nonce secret) so the entire rest of the computation - nonce point,
// nonce hash, challenge clamping, modular inverse, final r/s bytes - becomes one exact expected
// value instead of "structurally plausible". This is what "same algorithm, same result except the
// random nonce" (per the user's explicit requirement) is verified against.
const crossCheckPath = new URL('./fixtures/cross-check.json', import.meta.url);
const CROSS_CHECK: {
  kcdsa_sign: {
    private_key_hex: string;
    nonce_secret: string;
    data16_hex: string;
    signature_hex: string;
    attempts: number;
  };
} = JSON.parse(readFileSync(crossCheckPath, 'utf8'));

function hexToBytes(hex: string): Uint8Array {
  const out = new Uint8Array(hex.length / 2);
  for (let i = 0; i < out.length; i++) out[i] = parseInt(hex.slice(i * 2, i * 2 + 2), 16);
  return out;
}

describe('mikrotikKcdsaSign with a fixed nonce matches the real Python kcdsaSign byte-for-byte', () => {
  it('reproduces the exact 48-byte signature Python produced for the same key/data/nonce', () => {
    const { private_key_hex, nonce_secret, data16_hex, signature_hex, attempts } =
      CROSS_CHECK.kcdsa_sign;
    // The fixture's own `attempts: 1` means Python's fixed-nonce acceptance check passed on the
    // very first try for this particular (key, data, nonce) triple - if this ever needed >1
    // attempt the fixture itself would be unusable for a fixed-nonce comparison (Python's
    // fixed-nonce mode does not retry, see signature.py), so this assertion protects the fixture's
    // own precondition, not mikrotikKcdsaSign.
    expect(attempts).toBe(1);
    const privateKey = hexToBytes(private_key_hex);
    const data = hexToBytes(data16_hex);
    const sig = mikrotikKcdsaSign(data, privateKey, BigInt(nonce_secret));
    expect(Buffer.from(sig).toString('hex')).toBe(signature_hex);
  });
});

// Cross-language ground truth for the VERIFY side specifically: generated by calling the real,
// hardware-validated Python `verify_with_point()` (tools/scripts/verify_license.py) directly -
// not by re-deriving from mikrotikKcdsaSign's own internal check, which is how this function was
// originally written before this fixture existed (see Kcdsa.ts's comment on the function).
const verifyCrossCheckPath = new URL('./fixtures/verify-cross-check.json', import.meta.url);
const VERIFY_CROSS_CHECK: {
  pubkey_x_hex: string;
  pubkey_y_hex: string;
  data16_hex: string;
  tampered_data16_hex: string;
  signature_hex: string;
  verify_with_point_correct: boolean;
  verify_with_point_tampered: boolean;
} = JSON.parse(readFileSync(verifyCrossCheckPath, 'utf8'));

function hexToBytesForVerify(hex: string): Uint8Array {
  const out = new Uint8Array(hex.length / 2);
  for (let i = 0; i < out.length; i++) out[i] = parseInt(hex.slice(i * 2, i * 2 + 2), 16);
  return out;
}

describe('mikrotikKcdsaVerify matches the real Python verify_with_point()', () => {
  it('accepts the valid signature and rejects the tampered one, same as Python', () => {
    const publicKey = {
      x: BigInt('0x' + VERIFY_CROSS_CHECK.pubkey_x_hex),
      y: BigInt('0x' + VERIFY_CROSS_CHECK.pubkey_y_hex),
    };
    const signature = hexToBytesForVerify(VERIFY_CROSS_CHECK.signature_hex);

    const resultCorrect = mikrotikKcdsaVerify(
      hexToBytesForVerify(VERIFY_CROSS_CHECK.data16_hex),
      signature,
      publicKey,
    );
    const resultTampered = mikrotikKcdsaVerify(
      hexToBytesForVerify(VERIFY_CROSS_CHECK.tampered_data16_hex),
      signature,
      publicKey,
    );

    expect(resultCorrect).toBe(VERIFY_CROSS_CHECK.verify_with_point_correct);
    expect(resultTampered).toBe(VERIFY_CROSS_CHECK.verify_with_point_tampered);
    // Guard against a degenerate fixture where both booleans happened to match by both being
    // the same value - the whole point is that valid/tampered must actually disagree.
    expect(VERIFY_CROSS_CHECK.verify_with_point_correct).toBe(true);
    expect(VERIFY_CROSS_CHECK.verify_with_point_tampered).toBe(false);
  });
});

describe('bytesToIntLE / intToBytesLE', () => {
  it('round-trips arbitrary-length values without precision loss', () => {
    const bytes = new Uint8Array([0x35, 0x4c, 0xaf, 0xfb, 0xfb, 0x8f, 0x0d, 0xf3]);
    const asInt = bytesToIntLE(bytes);
    expect(asInt > BigInt(Number.MAX_SAFE_INTEGER)).toBe(true);
    expect(intToBytesLE(asInt, bytes.length)).toEqual(bytes);
  });

  it('silently truncates high bits and zero-pads, matching the Python original', () => {
    expect(intToBytesLE(0x1_00n, 1)).toEqual(new Uint8Array([0x00]));
    expect(intToBytesLE(5n, 4)).toEqual(new Uint8Array([5, 0, 0, 0]));
  });
});

describe('mikrotikKcdsaSign / mikrotikKcdsaVerify', () => {
  const privateKey = new Uint8Array(32);
  crypto.getRandomValues(privateKey);
  const publicKey = mikrotikKcdsaPublicKey(privateKey);
  const message = new TextEncoder().encode('license-payload-under-test');

  it('produces a signature that satisfies its own internal verification equation, across many random keys/messages', () => {
    // Reduced from 200: after fixing the asymmetric mod bug (checkPoint.x must be compared RAW,
    // not mod n), the retry loop now genuinely runs ~8x per signature on average (matching
    // Python), so 200 trials would be ~8x slower than the run that originally picked that number.
    for (let trial = 0; trial < 30; trial++) {
      const key = new Uint8Array(32);
      crypto.getRandomValues(key);
      const msg = new Uint8Array(16);
      crypto.getRandomValues(msg);
      const pub = mikrotikKcdsaPublicKey(key);
      const sig = mikrotikKcdsaSign(msg, key);
      expect(sig.length).toBe(48);
      expect(mikrotikKcdsaVerify(msg, sig, pub)).toBe(true);
    }
  }, 60000);

  it('rejects a signature checked against the wrong message', () => {
    const sig = mikrotikKcdsaSign(message, privateKey);
    const wrongMessage = new TextEncoder().encode('license-payload-tampered!');
    expect(mikrotikKcdsaVerify(wrongMessage, sig, publicKey)).toBe(false);
  });

  it('rejects a signature checked against the wrong public key', () => {
    const sig = mikrotikKcdsaSign(message, privateKey);
    const otherKey = new Uint8Array(32);
    crypto.getRandomValues(otherKey);
    const otherPub = mikrotikKcdsaPublicKey(otherKey);
    expect(mikrotikKcdsaVerify(message, sig, otherPub)).toBe(false);
  });

  it('never reuses the same nonce across two signatures of the same input (nonce reuse would leak the private key)', () => {
    const sigA = mikrotikKcdsaSign(message, privateKey);
    const sigB = mikrotikKcdsaSign(message, privateKey);
    expect(Buffer.from(sigA).toString('hex')).not.toBe(Buffer.from(sigB).toString('hex'));
    // both still independently valid despite differing
    expect(mikrotikKcdsaVerify(message, sigA, publicKey)).toBe(true);
    expect(mikrotikKcdsaVerify(message, sigB, publicKey)).toBe(true);
  });
});
