import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';
import {
  generateLicenseFromSoftwareId,
  softwareGroupsByte,
  softwareIdDecode,
} from '../src/LicenseFromSoftwareId';
import { LICENSE_FOOTER, LICENSE_HEADER } from '../src/LicenseFormat';
import { mikrotikKcdsaPublicKey, mikrotikKcdsaVerify } from '../src/Kcdsa';
import { customBase64Decode } from '../src/Base64';

// Cross-language ground truth: generated by calling the real Python
// `licenseGeneratorBySoftwareId()` (`tools/scripts/licenseBySoftwareId.py`) with
// `fixed_nonce_secret` pinned, plus a handful of `softwareIdDecode()` vectors - see this session's
// fixture-generation script. Satisfies "same algorithm, same result except the random nonce" for
// the Software-ID pathway the same way the System-ID cross-check does.
const crossCheckPath = new URL('./fixtures/cross-check.json', import.meta.url);
const CROSS_CHECK: {
  software_id_license: {
    private_key_hex: string;
    nonce_secret: string;
    software_id: string;
    major: number;
    level: number;
    groups: number;
    license_text: string;
  };
  software_id_decode: { software_id: string; expected_decimal_string: string }[];
} = JSON.parse(readFileSync(crossCheckPath, 'utf8'));

function hexToBytes(hex: string): Uint8Array {
  const out = new Uint8Array(hex.length / 2);
  for (let i = 0; i < out.length; i++) out[i] = parseInt(hex.slice(i * 2, i * 2 + 2), 16);
  return out;
}

describe('softwareIdDecode matches the Python reference', () => {
  it('loaded a non-trivial vector set', () => {
    expect(CROSS_CHECK.software_id_decode.length).toBeGreaterThan(3);
  });

  for (const { software_id, expected_decimal_string } of CROSS_CHECK.software_id_decode) {
    it(`decodes ${software_id} to the same integer as Python`, () => {
      expect(softwareIdDecode(software_id).toString()).toBe(expected_decimal_string);
    });
  }

  it('strips the dash the same way regardless of exact position', () => {
    expect(softwareIdDecode('AB12CD34')).toBe(softwareIdDecode('AB12-CD34'));
  });

  it('rejects a character outside the shared alphabet', () => {
    expect(() => softwareIdDecode('!!!!-!!!!')).toThrow(RangeError);
  });
});

describe('softwareGroupsByte matches the Python reference bit-packing', () => {
  it('packs groups into the high nibble and level into the low nibble', () => {
    expect(softwareGroupsByte(6, 1)).toBe(0x16);
    expect(softwareGroupsByte(0, 0)).toBe(0x00);
    expect(softwareGroupsByte(0x0f, 0x0f)).toBe(0xff);
  });

  it('rejects level/groups outside the 4-bit range', () => {
    expect(() => softwareGroupsByte(16, 1)).toThrow(RangeError);
    expect(() => softwareGroupsByte(1, 16)).toThrow(RangeError);
    expect(() => softwareGroupsByte(-1, 1)).toThrow(RangeError);
  });
});

describe('generateLicenseFromSoftwareId()', () => {
  it('reproduces the real Python licenseGeneratorBySoftwareId() output byte-for-byte (fixed nonce)', () => {
    const { private_key_hex, nonce_secret, software_id, major, level, groups, license_text } =
      CROSS_CHECK.software_id_license;
    const license = generateLicenseFromSoftwareId(software_id, hexToBytes(private_key_hex), {
      major,
      level,
      groups,
      fixedNonceSecret: BigInt(nonce_secret),
    });
    expect(license).toBe(license_text);
  });

  const privateKey = new Uint8Array(32);
  crypto.getRandomValues(privateKey);
  const FIXED_NONCE = 42n;

  it('wraps output in the START/END license markers with the expected 4-line shape', () => {
    const license = generateLicenseFromSoftwareId('AB12-CD34', privateKey, {
      fixedNonceSecret: FIXED_NONCE,
    });
    const lines = license.split('\n');
    expect(lines.length).toBe(5);
    expect(lines[0]).toBe(LICENSE_HEADER);
    expect(lines[3]).toBe(LICENSE_FOOTER);
    expect(lines[4]).toBe('');
  });

  it('defaults major=7, level=6, groups=1, matching the Python CLI defaults', () => {
    const withDefaults = generateLicenseFromSoftwareId('AB12-CD34', privateKey, {
      fixedNonceSecret: FIXED_NONCE,
    });
    const explicit = generateLicenseFromSoftwareId('AB12-CD34', privateKey, {
      major: 7,
      level: 6,
      groups: 1,
      fixedNonceSecret: FIXED_NONCE,
    });
    expect(withDefaults).toBe(explicit);
  });

  it('accepts softwareId as a pre-decoded bigint identically to the string form', () => {
    const decoded = softwareIdDecode('AB12-CD34');
    const fromString = generateLicenseFromSoftwareId('AB12-CD34', privateKey, {
      fixedNonceSecret: FIXED_NONCE,
    });
    const fromBigint = generateLicenseFromSoftwareId(decoded, privateKey, {
      fixedNonceSecret: FIXED_NONCE,
    });
    expect(fromString).toBe(fromBigint);
  });

  it('embeds a signature that verifies against the correct plaintext payload', () => {
    const license = generateLicenseFromSoftwareId('AB12-CD34', privateKey, {
      major: 7,
      level: 6,
      groups: 1,
      fixedNonceSecret: FIXED_NONCE,
    });
    const lines = license.split('\n');
    const blob = customBase64Decode(lines[1] + lines[2]);
    expect(blob.length).toBe(64);
    const sig = blob.subarray(16, 64);

    const publicKey = mikrotikKcdsaPublicKey(privateKey);
    const id = softwareIdDecode('AB12-CD34');
    const expectedPlaintext = new Uint8Array(16);
    let v = id;
    for (let i = 0; i < 6; i++) {
      expectedPlaintext[i] = Number(v & 0xffn);
      v >>= 8n;
    }
    expectedPlaintext[6] = 7; // major
    expectedPlaintext[7] = softwareGroupsByte(6, 1); // level=6, groups=1
    // expectedPlaintext[8..15] stay 0

    expect(mikrotikKcdsaVerify(expectedPlaintext, sig, publicKey)).toBe(true);
  });

  it('rejects a Software-ID that overflows 6 bytes (48 bits)', () => {
    expect(() =>
      generateLicenseFromSoftwareId(1n << 48n, privateKey, { fixedNonceSecret: FIXED_NONCE }),
    ).toThrow(RangeError);
    expect(() =>
      generateLicenseFromSoftwareId(-1n, privateKey, { fixedNonceSecret: FIXED_NONCE }),
    ).toThrow(RangeError);
  });

  it('rejects a major byte outside uint8 range', () => {
    expect(() =>
      generateLicenseFromSoftwareId('AB12-CD34', privateKey, {
        major: 256,
        fixedNonceSecret: FIXED_NONCE,
      }),
    ).toThrow(RangeError);
    expect(() =>
      generateLicenseFromSoftwareId('AB12-CD34', privateKey, {
        major: -1,
        fixedNonceSecret: FIXED_NONCE,
      }),
    ).toThrow(RangeError);
  });

  it('produces different output on repeated calls with the same input (signature nonce is random, not reused)', () => {
    const a = generateLicenseFromSoftwareId('AB12-CD34', privateKey);
    const b = generateLicenseFromSoftwareId('AB12-CD34', privateKey);
    expect(a).not.toBe(b);
    expect(a.split('\n')[0]).toBe(b.split('\n')[0]);
    expect(a.split('\n')[3]).toBe(b.split('\n')[3]);
  });
});
