import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';
import { decode, encode } from '../src/LicenseCipher';

// Cross-language ground truth: generated by calling the real Python `decode()`
// (`tools/mikrotik_license/cipher.py`) directly - itself already validated on the Python side
// against real CHR test vectors plus 2000+ random round-trip vectors (see that module's own
// docstring). This asserts TS's `decode()` matches Python's `decode()` byte-for-byte, not just
// that it round-trips with TS's own `encode()` (which would pass even if both were wrong in the
// same self-consistent way).
const fixturePath = new URL('./fixtures/decode-vectors.json', import.meta.url);
const VECTORS: { data16_hex: string; hdr_hex: string }[] = JSON.parse(
  readFileSync(fixturePath, 'utf8'),
);

function hexToBytes(hex: string): Uint8Array {
  const out = new Uint8Array(hex.length / 2);
  for (let i = 0; i < out.length; i++) out[i] = parseInt(hex.slice(i * 2, i * 2 + 2), 16);
  return out;
}

function bytesToHex(bytes: Uint8Array): string {
  return Array.from(bytes)
    .map((b) => b.toString(16).padStart(2, '0'))
    .join('');
}

describe('decode() matches the Python reference byte-for-byte', () => {
  it('loaded a non-trivial vector set', () => {
    expect(VECTORS.length).toBeGreaterThan(10);
  });

  for (const { data16_hex, hdr_hex } of VECTORS) {
    it(`recovers data16=${data16_hex} from hdr=${hdr_hex}`, () => {
      expect(bytesToHex(decode(hexToBytes(hdr_hex)))).toBe(data16_hex);
    });
  }
});

describe('decode() is the exact inverse of encode() (both directions)', () => {
  it('decode(encode(x)) === x for every vector', () => {
    for (const { data16_hex } of VECTORS) {
      const original = hexToBytes(data16_hex);
      expect(bytesToHex(decode(encode(original)))).toBe(data16_hex);
    }
  });

  it('encode(decode(x)) === x for every vector (round-trips the other way too)', () => {
    for (const { hdr_hex } of VECTORS) {
      const original = hexToBytes(hdr_hex);
      expect(bytesToHex(encode(decode(original)))).toBe(hdr_hex);
    }
  });
});

describe('decode() input validation matches encode()', () => {
  it('rejects anything other than exactly 16 bytes', () => {
    expect(() => decode(new Uint8Array(15))).toThrow(RangeError);
    expect(() => decode(new Uint8Array(17))).toThrow(RangeError);
    expect(() => decode(new Uint8Array(32))).toThrow(RangeError);
  });
});

describe('encode() now rejects non-16-byte input instead of silently mis-processing it', () => {
  it('rejects 32 bytes (a multiple of 4, but not 16 - this used to slip through)', () => {
    expect(() => encode(new Uint8Array(32))).toThrow(RangeError);
  });
});
