import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';
import { computeDeadline, LICENSE_DEADLINE_PERMANENT } from '../src/LicenseDeadline';

// Cross-language ground truth: generated by calling the real Python `compute_deadline()`
// (`tools/scripts/licenseBySystemId.py`) with a fixed, non-DST-boundary UTC instant. This exists
// specifically because the subscription formula is easy to get subtly wrong by "simplifying" it
// to `now + days*86400` - it isn't that, it truncates to the END of the PREVIOUS UTC calendar day
// first. Any change here that isn't a faithful re-derivation from the fixture is a regression.
const fixturePath = new URL('./fixtures/deadline-cross-check.json', import.meta.url);
const FIXTURE: {
  fixed_now_iso: string;
  fixed_now_epoch: number;
  trial_default: number;
  trial_days_30: number;
  permanent: number;
  subscription_default: number;
  subscription_days_366: number;
} = JSON.parse(readFileSync(fixturePath, 'utf8'));

const FIXED_NOW = new Date(FIXTURE.fixed_now_iso);

describe('computeDeadline matches the Python reference byte-for-byte', () => {
  it('loaded a fixed "now" that is actually fixed (sanity check on the fixture itself)', () => {
    expect(Math.floor(FIXED_NOW.getTime() / 1000)).toBe(FIXTURE.fixed_now_epoch);
  });

  it('trial: now + 60 days (default), preserving time-of-day', () => {
    expect(computeDeadline('trial', undefined, FIXED_NOW)).toBe(BigInt(FIXTURE.trial_default));
  });

  it('trial: now + N days when a custom day count is given', () => {
    expect(computeDeadline('trial', 30, FIXED_NOW)).toBe(BigInt(FIXTURE.trial_days_30));
  });

  it('permanent: always the 0xFFFFFFFF sentinel, `days` ignored', () => {
    expect(computeDeadline('permanent', undefined, FIXED_NOW)).toBe(BigInt(FIXTURE.permanent));
    expect(computeDeadline('permanent', 9999, FIXED_NOW)).toBe(BigInt(FIXTURE.permanent));
    expect(computeDeadline('permanent', undefined, FIXED_NOW)).toBe(LICENSE_DEADLINE_PERMANENT);
  });

  it('subscription: (today - 1 day) 23:59:59 UTC + 180 days (default) - NOT now + 180*86400', () => {
    const result = computeDeadline('subscription', undefined, FIXED_NOW);
    expect(result).toBe(BigInt(FIXTURE.subscription_default));
    // Explicitly prove this differs from the naive "just add days" formula, so a future
    // "simplification" back to that formula fails loudly instead of silently.
    const naive = BigInt(Math.floor(FIXED_NOW.getTime() / 1000) + 180 * 86400);
    expect(result).not.toBe(naive);
  });

  it('subscription: (today - 1 day) 23:59:59 UTC + N days when a custom day count is given', () => {
    expect(computeDeadline('subscription', 366, FIXED_NOW)).toBe(
      BigInt(FIXTURE.subscription_days_366),
    );
  });

  it('subscription truncates to 23:59:59 UTC of the PREVIOUS day regardless of the current time-of-day', () => {
    const earlyMorning = new Date('2026-09-13T00:00:01Z');
    const lateNight = new Date('2026-09-13T23:59:59Z');
    expect(computeDeadline('subscription', 180, earlyMorning)).toBe(
      computeDeadline('subscription', 180, lateNight),
    );
  });
});
