import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';
import { generateLicenseFromSystemId } from '../src/LicenseFromSystemId';
import { LICENSE_DEADLINE_PERMANENT } from '../src/LicenseDeadline';
import { LICENSE_HEADER, LICENSE_FOOTER } from '../src/LicenseFormat';
import { mikrotikKcdsaPublicKey, mikrotikKcdsaVerify } from '../src/Kcdsa';
import { systemIdDecode } from '../src/SystemId';
import { customBase64Decode } from '../src/Base64';

// Cross-language ground truth: generated by calling the real Python `licenseBySystemId()`
// (`tools/scripts/licenseBySystemId.py`, reconstructed inline against `mikrotik_license`'s
// primitives) with `fixed_nonce_secret` pinned - the ENTIRE license text becomes a single exact
// expected value, not just "structurally plausible", satisfying the "same algorithm, same result
// except the random nonce" requirement end-to-end (encode/cipher, custom base64, header/footer
// wrapping, and the KCDSA signature all included).
const crossCheckPath = new URL('./fixtures/cross-check.json', import.meta.url);
const CROSS_CHECK: {
  chr_license: {
    private_key_hex: string;
    nonce_secret: string;
    system_id: string;
    deadline: number;
    level: number;
    license_text: string;
  };
} = JSON.parse(readFileSync(crossCheckPath, 'utf8'));

function hexToBytes(hex: string): Uint8Array {
  const out = new Uint8Array(hex.length / 2);
  for (let i = 0; i < out.length; i++) out[i] = parseInt(hex.slice(i * 2, i * 2 + 2), 16);
  return out;
}

describe('generateLicenseFromSystemId()', () => {
  const privateKey = new Uint8Array(32);
  crypto.getRandomValues(privateKey);
  // Must be exactly 11 characters - systemIdDecode() now enforces the real System-ID format's
  // fixed length (see SystemId.ts) rather than accepting arbitrary-length strings.
  const systemIdStr = 'ABCDEFGHIJK';
  // Fixed nonce for every test in this file that doesn't specifically want to exercise randomness
  // (only the last test, "produces different output...", omits it) - makes every other assertion
  // fully deterministic instead of "passes most of the time", and removes any dependency on the
  // KCDSA retry loop's average ~8 attempts for test runtime.
  const FIXED_NONCE = 42n;

  it('reproduces the real Python licenseBySystemId() output byte-for-byte (fixed nonce)', () => {
    const { private_key_hex, nonce_secret, system_id, deadline, level, license_text } =
      CROSS_CHECK.chr_license;
    const license = generateLicenseFromSystemId(
      system_id,
      hexToBytes(private_key_hex),
      BigInt(deadline),
      level,
      BigInt(nonce_secret),
    );
    expect(license).toBe(license_text);
  });

  it('wraps output in the START/END license markers with the expected 4-line shape', () => {
    const license = generateLicenseFromSystemId(
      systemIdStr,
      privateKey,
      LICENSE_DEADLINE_PERMANENT,
      3,
      FIXED_NONCE,
    );
    const lines = license.split('\n');
    // header, partA, partB, footer, '' (trailing newline produces a trailing empty segment)
    expect(lines.length).toBe(5);
    expect(lines[0]).toBe(LICENSE_HEADER);
    expect(lines[3]).toBe(LICENSE_FOOTER);
    expect(lines[4]).toBe('');
    // the base64 payload split across lines 1/2 should recombine to a plausible base64 string
    const rejoined = lines[1] + lines[2];
    expect(rejoined).toMatch(/^[A-Za-z0-9+/]+=*$/);
  });

  it('accepts systemId as a pre-decoded bigint identically to the string form', () => {
    const decoded = systemIdDecode(systemIdStr);
    const fromString = generateLicenseFromSystemId(
      systemIdStr,
      privateKey,
      LICENSE_DEADLINE_PERMANENT,
      3,
      FIXED_NONCE,
    );
    const fromBigint = generateLicenseFromSystemId(
      decoded,
      privateKey,
      LICENSE_DEADLINE_PERMANENT,
      3,
      FIXED_NONCE,
    );
    // Same nonce + same effective plaintext (string form decodes to the same bigint) -> identical
    // output byte-for-byte, not just "same header/footer shape" - the whole point of pinning
    // FIXED_NONCE is that there is no remaining source of variation between these two calls.
    expect(fromString).toBe(fromBigint);
  });

  it('embeds a signature that verifies against the same private key, over the correct plaintext payload', () => {
    const license = generateLicenseFromSystemId(
      systemIdStr,
      privateKey,
      LICENSE_DEADLINE_PERMANENT,
      3,
      FIXED_NONCE,
    );
    const lines = license.split('\n');
    const base64Payload = lines[1] + lines[2];
    const blob = customBase64Decode(base64Payload);
    expect(blob.length).toBe(64); // 16-byte ciphertext + 48-byte signature

    const sig = blob.subarray(16, 64);
    // We don't have `decode()` yet (explicitly deferred), so we can't recover the plaintext from
    // the ciphertext to verify the *actual* embedded signature end-to-end. This only proves the
    // signature primitive itself is self-consistent for the known plaintext we constructed here,
    // by re-deriving what the 16-byte payload must have been from systemId + deadline + level.
    const publicKey = mikrotikKcdsaPublicKey(privateKey);
    const id = systemIdDecode(systemIdStr);
    const expectedPlaintext = new Uint8Array(16);
    const idBytes = new Uint8Array(8);
    let v = id;
    for (let i = 0; i < 8; i++) {
      idBytes[i] = Number(v & 0xffn);
      v >>= 8n;
    }
    expectedPlaintext.set(idBytes, 0);
    // deadline (4 bytes LE, 0xFFFFFFFF sentinel = permanent/no-expiry) + level (1 byte, the same
    // explicit value passed to generateLicenseFromSystemId above - level is now a real parameter,
    // not a hardcoded internal constant, so this must match the call site rather than an assumed
    // default)
    expectedPlaintext.set([0xff, 0xff, 0xff, 0xff, 3], 8);

    expect(mikrotikKcdsaVerify(expectedPlaintext, sig, publicKey)).toBe(true);
  });

  it('accepts an explicit trial deadline instead of the permanent sentinel', () => {
    const trialDeadline = 1893456000n; // arbitrary future unix timestamp, not a real product decision
    const license = generateLicenseFromSystemId(
      systemIdStr,
      privateKey,
      trialDeadline,
      3,
      FIXED_NONCE,
    );
    const lines = license.split('\n');
    const blob = customBase64Decode(lines[1] + lines[2]);
    const sig = blob.subarray(16, 64);

    const publicKey = mikrotikKcdsaPublicKey(privateKey);
    const id = systemIdDecode(systemIdStr);
    const expectedPlaintext = new Uint8Array(16);
    const idBytes = new Uint8Array(8);
    let v = id;
    for (let i = 0; i < 8; i++) {
      idBytes[i] = Number(v & 0xffn);
      v >>= 8n;
    }
    expectedPlaintext.set(idBytes, 0);
    let d = trialDeadline;
    const deadlineBytes = new Uint8Array(4);
    for (let i = 0; i < 4; i++) {
      deadlineBytes[i] = Number(d & 0xffn);
      d >>= 8n;
    }
    expectedPlaintext.set(deadlineBytes, 8);
    expectedPlaintext[12] = 3; // must match the level argument passed to generateLicenseFromSystemId above

    expect(mikrotikKcdsaVerify(expectedPlaintext, sig, publicKey)).toBe(true);
  });

  it('produces different output on repeated calls with the same input (signature nonce is random, not reused)', () => {
    // Deliberately NOT passing FIXED_NONCE here - this is the one test in the file whose entire
    // point is to exercise genuine randomness (the earlier flaky/slow version of this test relied
    // on the same uncontrolled randomness for every other assertion in the file too, which is why
    // it's now isolated to just this one).
    const a = generateLicenseFromSystemId(systemIdStr, privateKey, LICENSE_DEADLINE_PERMANENT, 3);
    const b = generateLicenseFromSystemId(systemIdStr, privateKey, LICENSE_DEADLINE_PERMANENT, 3);
    expect(a).not.toBe(b);
    // but the deterministic parts (header/footer, and therefore the plaintext+ciphertext prefix
    // baked into the first ~21 base64 chars covering the 16-byte ciphertext) stay stable in shape
    expect(a.split('\n')[0]).toBe(b.split('\n')[0]);
    expect(a.split('\n')[3]).toBe(b.split('\n')[3]);
  });
});
